name: Generate Task List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Minden vasárnap éjfélkor fut

jobs:
  generate_task_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate task list
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          > task_list.json

          echo "Task list generated: "
          cat task_list.json
