name: Generate Task List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Minden vasárnap éjfélkor fut

jobs:
  generate_task_list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate task list
        run: |
          curl -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          > task_list.json

          echo "Task list generated: "
          cat task_list.json

      - name: Send task list to Discord
        run: |
          task_list=$(jq -r '.[] | select(.state != "closed") | "* \(.title)\n  - Description: \(.body // "No description")\n  - State: \(.state)\n  - URL: \(.html_url)\n"' task_list.json)
          embed=$(jq -n --arg description "$task_list" '{embeds: [{title: "Task List", description: $description, color: 3447003}]}')
          echo "$embed" > payload.json
          curl -H "Content-Type: application/json" -d @payload.json ${{ secrets.DISCORD_WEBHOOK_URL }}
